### ISSUE TITLE
Issue with jquery selectable

### ISSUE THREAD

**Issue by bencagri** [vol-bob/table-scroll#2]
I'm trying to use horizontal scroll on my table. The scroll bar is shown. But I can not click to move.
I'm using selectable to select multiple cells. Jquery selectable detects the td. So that scroll is inside td, It can not be clicked. Besides, selectable also does not work.

How can I prevent this?

**Comment by vol-bob** [comment]
Could you please provide the link to your page, so I would better understand usage context.

**Comment by bencagri** [comment]
Hi, I'm working on local now. I can create a sample tonight. (Same as I use.)

**Comment by vol-bob** [comment]
Yeah, that should help.

**Comment by bencagri** [comment]
My code is like this.  http://jsfiddle.net/r1jhu2Ld/  (forget the html pls. just c/p)
Seems that its working. I can move scroll. (I guess, click issue based on my css).
But trying click one more to scroll, selectable function is running as I mentioned.

Ps : I'm using modals instead of alert. Just printing days that if jquery selected is running or not.

**Comment by bencagri** [comment]
Any idea my friend?

**Comment by vol-bob** [comment]
Oh sorry, I totally forgot about this
I'll try to respond today

**Comment by vol-bob** [comment]
You have two thead tags in your table. The second one should be renamed to tfoot
See updated example 
http://jsfiddle.net/r1jhu2Ld/1/

**Comment by bencagri** [comment]
i know. I changed it and tried again. If you click the scroll, you can still see the alert.

**Comment by vol-bob** [comment]
yes, because this scroll lives within table, and you attach widget  selectable to entire table .

I changed your jQuery selectors a bit 

http://jsfiddle.net/r1jhu2Ld/2/

**Comment by bencagri** [comment]
ohh so thank you. I missed that part.

**Comment by bencagri** [comment]
One more question, how can i disable vertical scroll? Horizontal is ok, I tried overflowY option, it still is shown. 

Thanks my friend.

**Comment by bencagri** [comment]
ahh, ok... when i increased rowsInScrollableArea option its gone. Awesome!

**Comment by vol-bob** [comment]
right, you can increased rowsInScrollableArea value
