### ISSUE TITLE
Table_scroll using rowspan

### ISSUE THREAD

**Issue by RobWilkinson** [vol-bob/table-scroll#3]
I am having trouble scrolling a table with a rowspan in it. it seems to have trouble with the rowspan and thinks it has fewer columns than it really has. The result is a scrollbar that appears inside the end of the table

**Comment by vol-bob** [comment]
Unfortunately rowspan in tbody are not supported

**Comment by RobWilkinson** [comment]
Ah ok. Sorry to hear that. Thank you for your response.

 

Regards,

Rob
