### ISSUE TITLE
Animation freeze in Firefox

### ISSUE THREAD

**Issue by Nomanoclass** [vol-bob/table-scroll#7]
Hello,
when I scroll up/down, the content move only when I release the mouse click.
And if I stop moving the cursor, the mouse click release itself.

Thank you for your futur responces.

**Comment by Nomanoclass** [comment]
UP @volodymyr-bobko

**Comment by volodymyr-bobko** [comment]
Hello, sorry for delayed response

I can't change this behavior. When I scroll table vertical I have to move scroll (DIV) between different table rows. I can do it only after user release a mouse button. In other case it'll stop scrolling immediately after I change the parent of DIV that I use to create a scroll.

Regards

**Comment by Nomanoclass** [comment]
But on Chrome it work :S

Ok thanks anyway.

**Comment by Nomanoclass** [comment]
I search an other solution at your plugin, I have discover this code, if it can help you.
http://jsfiddle.net/TweNm/
